[package]
name = "haversine-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.41", features = ["derive"]}
libc = "0.2.174"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
